export const mockLists = [
  {
    id: 1,
    title: "Morning Yoga Routine",
    category: "EXERCISE",
    time: "2025-05-01T07:30:00",
    description: "Start the day with a 30-minute yoga session.",
    note: "Try to include more stretching.",
    is_complete: false,
    user_id: 1,
  },
  {
    id: 2,
    title: "Drink 8 Glasses of Water",
    category: "HYDRATION",
    time: "2025-05-02T10:00:00",
    description: "Track water intake throughout the day.",
    note: null,
    is_complete: true,
    user_id: 1,
  },
  {
    id: 3,
    title: "Doctor's Appointment",
    category: "MEDICAL_CHECKUPS",
    time: "2025-05-03T15:00:00",
    description: "Annual physical exam with Dr. Smith.",
    note: "Bring medical records.",
    is_complete: false,
    user_id: 1,
  },
  {
    id: 4,
    title: "Meditation Session",
    category: "STRESS_MANAGEMENT",
    time: "2025-05-04T20:00:00",
    description: "Use Headspace for a guided meditation.",
    note: "Focus on breathing techniques.",
    is_complete: false,
    user_id: 1,
  },
  {
    id: 5,
    title: "Cook a Healthy Meal",
    category: "NUTRITION",
    time: "2025-05-05T18:30:00",
    description: "Prepare a balanced dinner with veggies and protein.",
    note: "Try a new quinoa recipe.",
    is_complete: true,
    user_id: 1,
  },
  {
    id: 6,
    title: "Call a Friend",
    category: "SOCIAL_WELLNESS",
    time: "2025-05-06T19:00:00",
    description: "Catch up with Sarah and check in on her.",
    note: "Ask about her new job.",
    is_complete: false,
    user_id: 1,
  },
  {
    id: 7,
    title: "Painting Session",
    category: "HOBBIES",
    time: "2025-05-07T14:00:00",
    description: "Work on landscape painting.",
    note: "Use the new watercolors.",
    is_complete: true,
    user_id: 1,
  },
  {
    id: 8,
    title: "Gratitude Journal",
    category: "EMOTIONAL_WELLNESS",
    time: "2025-05-08T21:30:00",
    description: "Write 3 things you're grateful for today.",
    note: null,
    is_complete: false,
    user_id: 1,
  },
  {
    id: 9,
    title: "Skincare Routine",
    category: "SELFCARE",
    time: "2025-05-09T22:00:00",
    description: "Cleanse, tone, moisturize before bed.",
    note: "Try the new serum.",
    is_complete: true,
    user_id: 1,
  },
  {
    id: 10,
    title: "Health Goals Planning",
    category: "HEALTH",
    time: "2025-05-10T16:00:00",
    description: "Set health goals for the next month.",
    note: "Include diet and exercise targets.",
    is_complete: false,
    user_id: 1,
  },
  {
    id: 11,
    title: "Go for a Morning Walk",
    category: "EXERCISE",
    time: "2025-05-24T06:45:00",
    description: "A brisk walk around the park.",
    note: "Wear walking shoes.",
    is_complete: false,
    user_id: 1,
  },
  {
    id: 12,
    title: "Try a New Healthy Recipe",
    category: "NUTRITION",
    time: "2025-05-25T17:00:00",
    description: "Cook a plant-based meal.",
    note: "Use lentils and spinach.",
    is_complete: true,
    user_id: 1,
  },
  {
    id: 13,
    title: "Hydration Challenge",
    category: "HYDRATION",
    time: "2025-05-26T09:00:00",
    description: "Complete 2 liters by noon.",
    note: "Use the water-tracking app.",
    is_complete: false,
    user_id: 1,
  },
  {
    id: 14,
    title: "Evening Reflection",
    category: "EMOTIONAL_WELLNESS",
    time: "2025-05-26T21:00:00",
    description: "Reflect on your emotions and journal.",
    note: "Focus on gratitude.",
    is_complete: false,
    user_id: 1,
  },
  {
    id: 15,
    title: "Home Spa Session",
    category: "SELFCARE",
    time: "2025-05-27T20:00:00",
    description: "Take a long bath and do skincare.",
    note: null,
    is_complete: true,
    user_id: 1,
  },
  {
    id: 16,
    title: "Board Game Night",
    category: "SOCIAL_WELLNESS",
    time: "2025-05-28T19:30:00",
    description: "Play with friends or family.",
    note: "Bring snacks.",
    is_complete: false,
    user_id: 1,
  },
  {
    id: 17,
    title: "Therapy Appointment",
    category: "STRESS_MANAGEMENT",
    time: "2025-05-28T11:00:00",
    description: "Monthly session with therapist.",
    note: "Review goals from last session.",
    is_complete: false,
    user_id: 1,
  },
  {
    id: 18,
    title: "Blood Pressure Check",
    category: "MEDICAL_CHECKUPS",
    time: "2025-05-29T08:30:00",
    description: "Monitor blood pressure in the morning.",
    note: "Use home device.",
    is_complete: true,
    user_id: 1,
  },
  {
    id: 19,
    title: "Digital Detox",
    category: "HEALTH",
    time: "2025-05-20T18:00:00",
    description: "No screens for 3 hours before bed.",
    note: "Read a book instead.",
    is_complete: false,
    user_id: 1,
  },
  {
    id: 20,
    title: "Practice a New Song",
    category: "HOBBIES",
    time: "2025-05-19T16:30:00",
    description: "Learn a new piece on guitar.",
    note: "Focus on finger-picking.",
    is_complete: true,
    user_id: 1,
  },
];
